include:
  - path: ./deploy/hadoop/hadoop.yml
  - path: ./deploy/spark/spark.yml
  - path: ./deploy/airflow/airflow.yml
  - path: ./deploy/prometheus/prometheus.yml
  - path: ./deploy/grafana/grafana.yml
  - path: ./deploy/postgres/postgres.yml
  - path: ./deploy/clickhouse/clickhouse.yml
  - path: ./deploy/api/api.yml
  - path: ./deploy/nlp/nlp.yml

networks:
  data_platform_net:
    name: data_platform_net
    driver: bridge
