include:
  - path: ./docker-compose/hadoop.yml
  - path: ./docker-compose/spark/spark.yml
  - path: ./docker-compose/airflow/airflow.yml
  - path: ./docker-compose/prometheus/prometheus.yml
  - path: ./docker-compose/visualisation/visualisation.yml
  - path: ./docker-compose/postgres/postgres.yml
  - path: ./docker-compose/clickhouse/clickhouse.yml
  - path: ./docker-compose/nlp/nlp.yml

networks:
  data_platform_net:
    name: data_platform_net
    driver: bridge
