services:
  superset:
    build: .
    container_name: ${HOST_SUPERSET}
    ports:
      - "127.0.0.1:${PORT_SUPERSET}:8088"
    volumes:
      - superset-volume:/app/superset_data
      - ../../superset:/superset-mount
    environment:
      SUPERSET_CONFIG_PATH: /superset-mount/conf/superset_config.py
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SUPERSET_DB_URI: postgresql+psycopg2://${SUPERSET_PG_USER}:${SUPERSET_PG_PASS}@${HOST_SUPERSET_POSTGRES}:5432/${SUPERSET_PG_DB}
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      SUPERSET_ADMIN_USERNAME: ${SUPERSET_ADMIN_USERNAME}
      SUPERSET_ADMIN_PASSWORD: ${SUPERSET_ADMIN_PASSWORD}
      SUPERSET_ADMIN_FIRSTNAME: ${SUPERSET_ADMIN_FIRSTNAME}
      SUPERSET_ADMIN_LASTNAME: ${SUPERSET_ADMIN_LASTNAME}
      SUPERSET_ADMIN_EMAIL: admin@${DOMAIN}
    command: ["/bin/bash", "/superset-mount/conf/start-superset.sh"]
    restart: unless-stopped
    networks:
      - data_platform_net
    depends_on:
      superset-postgres:
        condition: service_healthy

  superset-postgres:
    image: postgres:17
    container_name: ${HOST_SUPERSET_POSTGRES}
    environment:
      POSTGRES_USER: ${SUPERSET_PG_USER}
      POSTGRES_PASSWORD: ${SUPERSET_PG_PASS}
      POSTGRES_DB: ${SUPERSET_PG_DB}
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=128MB"
      - "-c"
      - "effective_cache_size=256MB"
      - "-c"
      - "work_mem=8MB"
    volumes:
      - superset-postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${SUPERSET_PG_USER}", "-d", "${SUPERSET_PG_DB}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    networks:
      - data_platform_net

  grafana:
    image: grafana/grafana-enterprise:11.6.1
    container_name: ${HOST_GRAFANA}
    ports:
      - "127.0.0.1:${PORT_GRAFANA}:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_SERVER_ROOT_URL: https://${GRAFANA_SUBDOMAIN}.${DOMAIN}
      GF_SERVER_DOMAIN: ${GRAFANA_SUBDOMAIN}.${DOMAIN}
      GF_SECURITY_CSRF_TRUSTED_ORIGINS: ${GRAFANA_SUBDOMAIN}.${DOMAIN}
    volumes:
      - ../../grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ../../grafana/provisioning/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ../../grafana/dashboards-json:/var/lib/grafana/dashboards
      - grafana-volume:/var/lib/grafana
    restart: unless-stopped
    networks:
      - data_platform_net
    depends_on:
      - prometheus

volumes:
  superset-volume:
  superset-postgres-volume:
  grafana-volume:
