include "../base/base.conf"

Network {
    requestsPerSecond = 3
}

FileSystem {
    platform = "Adzuna"
}

Arguments {
    locationTags  = ["us",  "gb",    "pl",  "de",  "in",  "ca"]
    currencies    = ["USD", "GBP",   "PLN", "EUR", "INR", "CAD"]
    urlDomains    = ["com", "co.uk", "pl",  "de",  "in",  "ca"]
    appKeyIndexes = [0,     0,       0,     1,     1,     1]

    maxDaysOld  = 2
    vacsPerPage = 50    # <= 50
    pageLimit   = 9    # <= 20
    categoryTag = "it-jobs"

    expireAfterDays = 30

    appIds  = []
    appKeys = []

    apiBaseUrl = "https://api.adzuna.com/v1/api"
}

Dags {
    ETL {
        schedule = "0 3 * * *"
    }
}

include "../secrets/local_az.conf"
