include "../base/base.conf"

Network {
    requestsPerSecond = 3
}

FileSystem {
    platform = "Adzuna"
}

Arguments {
    locationTags = ["us", "gb", "pl"]
    currencies   = ["USD", "GBP", "PLN"]
    urlDomains   = ["com", "co.uk", "pl"]

    maxDaysOld  = 2
    vacsPerPage = 50    # <= 50
    pageLimit   = 9     # <= 20
    categoryTag = "it-jobs"

    expireAfterDays = 30

    appId  = ""
    appKey = ""

    apiBaseUrl = "https://api.adzuna.com/v1/api"
}

Dags {
    ETL {
        schedule = "0 3 * * *"
    }
}

include "../secrets/local_az.conf"
