include "../base/base.conf"
include "../secrets/local_exchangerate.conf"

FileSystem {
    platform = "ExchangeRate"
}

Arguments {
    apiBaseUrl = "https://v6.exchangerate-api.com/v6"
}

Dags {
    ETL {
        schedule = "0 0 * * *"
    }
}
