DataBase {
    host         = "app-postgres"
    port         = "5432"
    baseName     = "vacstorage"
    userName     = "postgres"
    userPassword = "1234"

    maxPartitions = 5
    batchSize     = 3000
}

FileSystem {
    url      = "hdfs://namenode:9000"
    path     = "VacStorage"
    platform = "unknown"
}

include "../secrets/local_infrastructure.conf"