DataBase {
    host         = ${HOST_APP_POSTGRES}
    port         = "5432"
    baseName     = ${PG_DB}
    userName     = ${PG_USER}
    userPassword = ${PG_PASS}

    maxPartitions = 5
    batchSize     = 3000
}

FileSystem {
    url      = "hdfs://"${HOST_NAMENODE}":9000"
    path     = "VacStorage"
    platform = "unknown"
}
