Spark {
    name           = "SparkApp"
    master         = "spark://spark-master:7077"
    driverMemory   = "1g"
    driverCores    = "1"
    executorMemory = "10g"
    executorCores  = "10"
}

include "../secrets/local_spark.conf"