Spark {
    name           = "SparkApp"
    master         = "spark://"${HOST_SPARK_MASTER}":7077"
    driverMemory   = "1g"
    driverCores    = "1"
    executorMemory = "3g"
    executorCores  = "2"
}
