services:
  superset:
    build: .
    container_name: ${HOST_SUPERSET}
    ports:
      - "127.0.0.1:${PORT_SUPERSET}:8088"
    volumes:
      - superset-volume:/app/superset_data
      - .:/superset-mount
    environment:
      SUPERSET_CONFIG_PATH: /superset-mount/conf/superset_config.py
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SUPERSET_DB_URI: postgresql+psycopg2://${SUPERSET_PG_USER}:${SUPERSET_PG_PASS}@${HOST_SUPERSET_POSTGRES}:5432/${SUPERSET_PG_DB}
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      SUPERSET_ADMIN_USERNAME: ${SUPERSET_ADMIN_USERNAME}
      SUPERSET_ADMIN_PASSWORD: ${SUPERSET_ADMIN_PASSWORD}
      SUPERSET_ADMIN_FIRSTNAME: ${SUPERSET_ADMIN_FIRSTNAME}
      SUPERSET_ADMIN_LASTNAME: ${SUPERSET_ADMIN_LASTNAME}
      SUPERSET_ADMIN_EMAIL: admin@${DOMAIN}

      CH_USER: ${CH_USER}
      CH_PASS: ${CH_PASS}
      CH_DB: ${CH_DB}
      HOST_CLICKHOUSE: ${HOST_CLICKHOUSE}

    command: ["/bin/bash", "/superset-mount/conf/start-superset.sh"]
    restart: unless-stopped
    networks:
      - data_platform_net
    depends_on:
      superset-postgres:
        condition: service_healthy

  superset-postgres:
    image: postgres:17
    container_name: ${HOST_SUPERSET_POSTGRES}
    environment:
      POSTGRES_USER: ${SUPERSET_PG_USER}
      POSTGRES_PASSWORD: ${SUPERSET_PG_PASS}
      POSTGRES_DB: ${SUPERSET_PG_DB}
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=128MB"
      - "-c"
      - "effective_cache_size=256MB"
      - "-c"
      - "work_mem=8MB"
    volumes:
      - superset-postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${SUPERSET_PG_USER}", "-d", "${SUPERSET_PG_DB}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    networks:
      - data_platform_net

volumes:
  superset-volume:
  superset-postgres-volume:
