include "../secrets/local_airflow.conf"

FileSystem {
    path = "VacStorage"
}

Dags {
    ETL {
        minRows = 1
    }

    RefreshMatViews {
        schedule = "30 0 * * *"
    }

    DeleteData {
        schedule = "30 10 * * *"
        rawData = 30
        airflowLogs = 7
    }

    BackupDB {
        schedule  = ""
        keepDumps = 3
    }
}