x-airflow-common:
  &airflow-common
  build: .
  env_file:
    - .env
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR:-LocalExecutor}
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN:-postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY:-}
    AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW__CORE__LOAD_EXAMPLES:-False}
    AIRFLOW__API__AUTH_BACKENDS: ${AIRFLOW__API__AUTH_BACKENDS:-airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session}
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: ${AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK:-True}
    AIRFLOW__WEBSERVER__BASE_URL: ${AIRFLOW__WEBSERVER__BASE_URL:-http://localhost:8080}
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY:-46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=}
    AIRFLOW__WEBSERVER__WORKERS: ${AIRFLOW__WEBSERVER__WORKERS:-1}
    AIRFLOW_CONN_SPARK_CONN: ${AIRFLOW_CONN_SPARK_CONN:-spark://spark-master:7077}
    AIRFLOW_CONN_POSTGRES_CONN: ${AIRFLOW_CONN_POSTGRES_CONN:-postgres://postgres:1234@app-postgres/vacstorage}
    AIRFLOW_CONN_CLICKHOUSE_CONN: ${AIRFLOW_CONN_CLICKHOUSE_CONN:-http://admin:password@clickhouse:8123/analytics}
    AIRFLOW_VAR_SPARK_SUBMIT: ${AIRFLOW_VAR_SPARK_SUBMIT:-}
    AIRFLOW__METRICS__STATSD_ON: ${AIRFLOW__METRICS__STATSD_ON:-True}
    AIRFLOW__METRICS__STATSD_HOST: ${AIRFLOW__METRICS__STATSD_HOST:-statsd-exporter}
    AIRFLOW__METRICS__STATSD_PORT: ${AIRFLOW__METRICS__STATSD_PORT:-9125}
    AIRFLOW__METRICS__STATSD_PREFIX: ${AIRFLOW__METRICS__STATSD_PREFIX:-airflow}
  volumes:
    - ../../airflow/dags:/opt/airflow/dags
    - ../../jobs/scala_ETL_project:/opt/airflow/scalaProject
    - airflow-volume:/opt/airflow/logs
    - ../../conf:/opt/airflow/conf
  user: "${AIRFLOW_UID:-50000}:0"
  networks:
    - data_platform_net
  depends_on:
    &airflow-common-depends-on
    airflow-postgres:
      condition: service_healthy


services:
  airflow-webserver:
    <<: *airflow-common
    command: ["airflow", "webserver", "--debug", "--port", "8080"]
    container_name: airflow-webserver
    ports:
      - "127.0.0.1:11080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
      airflow-scheduler:
        condition: service_healthy

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    container_name: airflow-scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    container_name: airflow-init
    restart: "no"
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags}
        exec /entrypoint airflow version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"
    volumes:
      - ../../airflow:/sources

  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    restart: "no"
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    command:
      - bash
      - -c
      - airflow

  airflow-postgres:
    image: postgres:15-alpine
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: ${AIRFLOW_PG_USER:-airflow}
      POSTGRES_PASSWORD: ${AIRFLOW_PG_PASSWORD:-airflow}
      POSTGRES_DB: ${AIRFLOW_PG_DB:-airflow}
    volumes:
      - airflow-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${AIRFLOW_PG_USER:-airflow}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    networks:
      - data_platform_net

  statsd-exporter:
    image: prom/statsd-exporter:v0.28.0
    container_name: statsd-exporter
    command: "--statsd.mapping-config=/tmp/statsd_mapping.yml"
    volumes:
      - ./statsd_mapping.yml:/tmp/statsd_mapping.yml
    restart: unless-stopped
    networks:
      - data_platform_net

volumes:
  airflow-db-volume:
  airflow-volume: